# http
server:
  port: 5050
  servlet:
    context-path: /api

# socket
ws:
  port: 5051

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: chat-service
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

logging:
  level:
    com:
      salmon:
        chatService: debug